---
sudo: false
cache:
  directories:
    - $HOME/.cpanm
    - $HOME/.nvm
    - $HOME/perl5/perlbrew/perls/5.16/lib/site_perl
    - /var/tmp
addons:
  apt_packages:
    - libmpfr-dev
before_install:
  - export HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
  - git config --global user.name "Dist Zilla Plugin TravisCI"
  - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
install:
  - npm install -g uglify-js handlebars
  - cpanm --quiet --notest Dist::Zilla
  - dzil authordeps | grep -ve '^\W' | xargs -n 5 -P 10 cpanm --skip-satisfied --quiet --notest --mirror http://www.cpan.org/ --mirror http://duckpan.org
  - which bzip2
  - perl -MLWP::UserAgent -e 'LWP::UserAgent->new->mirror("http://ddg-community.s3.amazonaws.com/metadata/repo_all.json.bz2", "/var/tmp/ddg-metadata-1000/metadata.json.bz2")' 
  - ls -al /var/tmp
  - ls -al /var/tmp/ddg*
  - perl -MDDG::Meta::Data -e 'warn DDG::Meta::Data->get_ia(id => q(reverse))->{name}'
  - ls -al /var/tmp/ddg-metadata-1000
  - dzil listdeps | grep -ve '^\W' | cpanm --skip-satisfied --quiet --notest --mirror http://www.cpan.org/ --mirror http://duckpan.org
language: perl
perl:
  - 5.16
script:
  - dzil smoke --release --author
